#!/bin/bash
set -e

BUILD_ROOT=$1

UNAMEARCH=`uname -m`
if [[ $UNAMEARCH == "x86_64" ]] ; then
   EFIARCH=x64
elif [[ $UNAMEARCH == "i686" || $UNAMEARCH == "i586" || $UNAMEARCH == "i486" || $UNAMEARCH == "i386" ]] ; then
   EFIARCH=ia32
else
   EFIARCH=$UNAMEARCH
fi

mkdir -p $BUILD_ROOT/usr/share/refind/refind/

install -Dp -m0644 gptsync/gptsync_$EFIARCH.efi $BUILD_ROOT/usr/share/refind/refind/tools_$EFIARCH/gptsync_$EFIARCH.efi

echo "*** Exiting debinstall! ***"
