drivers_* usr/share/refind/refind
refind.conf-sample usr/share/refind/refind
refind/refind*.efi usr/share/refind/refind

icons/*.png usr/share/refind/refind/icons
icons/README usr/share/refind/refind/icons

banners usr/share/refind
fonts usr/share/refind

mkrlconf usr/sbin
mvrefind usr/sbin
refind-install usr/share/refind
# refind-install symlink is added to usr/sbin as well (see refind.links)

keys etc/refind
